### ISSUE TITLE
Cann't install on CentOS 7 without python3-passlib

### ISSUE THREAD

**Issue by Maksold** [geerlingguy/ansible-role-htpasswd#5]
```
TASK [geerlingguy.htpasswd : Ensure the htpasswd utility is installed.] ********************************************************************************************************************************************************************************************************
fatal: [64.227.118.153]: FAILED! => {"changed": false, "msg": "No package matching 'python3-passlib' found available, installed or updated", "rc": 126, "results": ["No package matching 'python3-passlib' found available, installed or updated"]}
```

@geerlingguy How can I install python3-passlib on CentOS 7? 

I tried https://github.com/geerlingguy/ansible-role-pip with 
```
pip_package: python3-pip
pip_install_packages:
  - passlib
```

But it doesn't work. Maybe you have a solution for that?

**Comment by geerlingguy** [comment]
Can you try `python-passlib` instead and see if that works?

**Comment by Maksold** [comment]
I tried to install python-passlib, but it installs it for python 2 and as a result, geerlingguy.htpasswd role doesn't work, because it requires python3.

**Comment by geerlingguy** [comment]
Ah... `htpasswd_required_packages` is defined in `vars` files so it can't be overridden.

I should make that a configurable variable, so you can define your own version of passlib to be installed, so it can work correctly on CentOS 7 where, often, Python 2 is a requirement and Python 3 can result in breakage.

**Comment by Maksold** [comment]
@geerlingguy How fast could you fix it or better would be to make a pull request?

**Comment by geerlingguy** [comment]
Fixed via above commit!
